services:
  postgres:
    image: postgres:latest
    command: -c "max_connections=5000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 3s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
