name: Test

on:
  pull_request:
    branches:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env: |
          POSTGRES_USER=postgres
          POSTGRES_PASSWORD=password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
        timeout-minutes: 0.5
        continue-on-error: true

      - name: Verify Yarn cache
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: mkdir -p ~/.cache/yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        env:
          POSTGRES_URL: "postgresql://postgres:password@127.0.0.1:5432/postgres?schema=public"
        run: env && yarn test
